query drugApprovalWithdrawnWarningData {
  drug(chemblId: "CHEMBL118") {
    name
    id
    drugWarnings {
      warningType
      description
      toxicityClass
      year
      references {
        id
        source
        url
      }
    }
  }
}
