query ChemicalProbes($ensemblId: String!) {
  target(ensemblId: $ensemblId) {
    id
    chemicalProbes {
      id
      control
      drugId
      isHighQuality
      mechanismOfAction
      origin
      probeMinerScore
      probesDrugsScore
      scoreInCells
      scoreInOrganisms
      targetFromSourceId
      urls {
        niceName
        url
      }
    }
  }
}
