query ChemicalProbesQuery($ensemblId: String!) {
  target(ensemblId: $ensemblId) {
    id
    chemicalProbes {
          id
          control
          drugId
          inchiKey
          mechanismOfAction
          origin
          isHighQuality
          probeMinerScore
          probesDrugScore
          scoreInCells
          scoreInOrganisms
          targetFromSourceId
          urls {
            niceName
            url
          }
        }
    }
  }
}
