query ChemblQuery($ensemblId: String!, $efoId: String!, $size: Int!, $cursor: String) {
  disease(efoId: $efoId) {
    id
    chembl: evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["clinical_precedence"]
      size: $size
      cursor: $cursor
    ) {
      cursor
      count
      rows {
        disease {
          id
          name
        }
        target {
          id
          approvedSymbol
        }
        drug {
          id
          name
          drugType
          mechanismsOfAction {
            rows {
              mechanismOfAction
              targets {
                id
                approvedSymbol
              }
            }
          }
        }
        variantEffect
        directionOnTrait
        targetFromSourceId
        clinicalStage
        clinicalReportId
        studyStartDate
        trialWhyStopped
        trialStopReasonCategories
      }
    }
  }
}
