query Depmap ($ensemblId: String!) {
  target(ensemblId: $ensemblId) {
    id
    depMapEssentiality {
      tissueName
      screens{
        depmapId
        cellLineName
        diseaseFromSource
        geneEffect
        expression
      }
    }
  }
}
