fragment DrugProfileHeaderFragment on Drug {
  description
  drugType
  synonyms
  parentMolecule {
    id
    name
  }
  childMolecules {
    id
    name
  }
  maximumClinicalStage
  tradeNames
  yearOfFirstApproval
}
