query EvaSomaticQuery($ensemblId: String!, $efoId: String!, $size: Int!, $cursor: String) {
  disease(efoId: $efoId) {
    id
    eva_somatic: evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["eva_somatic"]
      size: $size
      cursor: $cursor
    ) {
      cursor
      count
      rows {
        disease {
          id
          name
        }
        variantEffect
        directionOnTrait
        diseaseFromSource
        variantId
        variantRsId
        variantHgvsId
        studyId
        clinicalSignificances
        allelicRequirements
        alleleOrigins
        confidence
        literature
        cohortPhenotypes
      }
    }
  }
  target(ensemblId: $ensemblId) {
    id
    hallmarks {
      attributes {
        description
        pmid
        name
      }
    }
  }
}
