query GenomicsEnglandQuery($ensemblId: String!, $efoId: String!, $size: Int!) {
  target(ensemblId: $ensemblId) {
    approvedSymbol
  }
  disease(efoId: $efoId) {
    id
    name
    genomicsEngland: evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["genomics_england"]
      size: $size
    ) {
      count
      rows {
        disease {
          id
          name
        }
        target {
          approvedSymbol
        }
        diseaseFromSource
        cohortPhenotypes
        confidence
        allelicRequirements
        studyOverview
        studyId
        confidence
        literature
      }
    }
  }
}
