query OpenTargetsGeneticsQuery($ensemblId: String!, $efoId: String!, $size: Int!) {
  target(ensemblId: $ensemblId) {
    approvedSymbol
  }
  disease(efoId: $efoId) {
    id
    name
    openTargetsGenetics: evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["ot_genetics_portal"]
      size: $size
    ) {
      count
      rows {
        id
        disease {
          id
          name
        }
        variantEffect
        directionOnTrait
        diseaseFromSource
        studyId
        studySampleSize
        variantId
        variantRsId
        literature
        publicationYear
        publicationFirstAuthor
        pValueExponent
        pValueMantissa
        oddsRatio
        oddsRatioConfidenceIntervalLower
        oddsRatioConfidenceIntervalUpper
        beta
        betaConfidenceIntervalLower
        betaConfidenceIntervalUpper
        variantFunctionalConsequence {
          id
          label
        }
        variantFunctionalConsequenceFromQtlId {
          id
          label
        }
        resourceScore
        projectId
      }
    }
  }
}
