query reactomeQuery($ensemblId: String!, $efoId: String!, $size: Int!) {
  target(ensemblId: $ensemblId) {
    approvedSymbol
  }
  disease(efoId: $efoId) {
    id
    reactomeSummary: evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["reactome"]
      size: $size
    ) {
      count
      rows {
        disease {
          id
          name
        }
        diseaseFromSource
        reactionName
        reactionId
        targetFromSourceId
        pathways {
          id
          name
        }
        targetModulation
        variantAminoacidDescriptions
        literature
      }
    }
  }
}
