query Safety($ensemblId: String!) {
  target(ensemblId: $ensemblId) {
    id
    safetyLiabilities {
      event
      eventId
      biosamples {
        cellFormat
        cellLabel
        tissueLabel
        tissueId
      }
      effects {
        dosing
        direction
      }
      studies {
        name
        type
        description
      }
      datasource
      literature
      url
    }
  }
}
