query SysBioQuery($ensemblId: String!, $efoId: String!, $size: Int!) {
  target(ensemblId: $ensemblId) {
    approvedSymbol
  }
  disease(efoId: $efoId) {
    id
    sysBio: evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["sysbio"]
      size: $size
    ) {
      count
      rows {
        disease {
          id
          name
        }
        target {
          id
          approvedSymbol
        }
        studyOverview
        literature
        pathways {
          name
        }
      }
    }
  }
}
