query UniprotVariantsQuery($ensemblId: String!, $efoId: String!, $size: Int!) {
  target(ensemblId: $ensemblId) {
    approvedSymbol
  }
  disease(efoId: $efoId) {
    id
    uniprotVariantsSummary: evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["uniprot_variants"]
      size: $size
    ) {
      count
      rows {
        disease {
          id
          name
        }
        diseaseFromSource
        targetFromSourceId
        variantRsId
        confidence
        literature
      }
    }
  }
}
